# Generated by Django 3.1.4 on 2021-01-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='ecom.jpg', null=True, upload_to='images'),
        ),
    ]
